staging:
  adapter: postgresql
  database: BMS_staging

production:
  adapter: postgresql
  database:
  username:
  password:
  host:

development:
  adapter: postgresql
  database: BMS_development

test:
  adapter: postgresql
  database: BMS_test
  min_messages: warning
